Созданы юнит тесты для тестирования класса BooksCollector, заполнена Readme, создан и заполнен файл .gitignore
Vikhu23/qa_python_sprint_2 pull request #2
Opened 2023-07-01 04:02 UTC by Vikhu23

2023-07-03 06:48 UTC, kadirovgm requested changes

2023-07-03 06:48 UTC, kadirovgm commented on README.md
> +
Можно лучше: в readme также можно добавить описание проекта, использованные библиотеки и зависимости, описание тестов

Советую также верстать описание в формате Markdown

2023-07-03 06:48 UTC, kadirovgm commented on __pycache__/conftest.cpython-311-pytest-7.3.2.pyc
нужно исправить: этот файл не относится к проекту, его нужно либо удалить либо добавить в гитигнор, мы не должны мержить в общий репозиторий лишние файлы

2023-07-03 06:48 UTC, kadirovgm commented on __pycache__/main.cpython-311.pyc
нужно исправить: этот файл не относится к проекту, его нужно либо удалить либо добавить в гитигнор, мы не должны мержить в общий репозиторий лишние файлы

2023-07-03 06:48 UTC, kadirovgm commented on __pycache__/tests.cpython-311-pytest-7.3.2.pyc
нужно исправить: этот файл не относится к проекту, его нужно либо удалить либо добавить в гитигнор, мы не должны мержить в общий репозиторий лишние файлы

2023-07-03 06:48 UTC, kadirovgm commented on conftest.py
> +@pytest.fixture(scope='function')
можно лучше: scope=function уже по умолчанию так, так что явно можно не прописывать, в отличии от scope=class, scope=session

2023-07-03 06:48 UTC, kadirovgm commented on conftest.py
> +def book_rating():
можно лучше: выглядит как спорное решение для частного случая

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_books_rating()) != 2
нужно исправить: лучше явно проверить что книг в словаре = 1, или что в словаре находится именна та книга, которую добавили

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('Горе от ума') != 10
нужно исправить: кажется правильнее будет првоерить, что рейтинг is Empty, тест должен явно проверять ожидание, а не косвенно, ведь не равно 10, может означать, что оно равно 1, например.

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +    def test_set_rating_book_less_than_1_not_setting(self, book_name):
нужно исправить: для таких невалидных значений у тебя написано два одинаковых теста, которые все ожидают рейтинг = 1 (для -1, 11, 0). В таком случае надо избегать повторений кода и воспользоваться параметризацией этих невалидных значений

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating(book_name) != 11
нужно исправить: стоит проверить, что при рейтинге 11, будет выстален рейтинг 1 (это по заданию)

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_rating() != 0
нужно исправить: если я правильно понял твой тест по названию, то ты проверяешь, что у книги нет рейтинга, тогда лучше воспользоваться методом `get_book_rating`

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 1
можно лучше: здесь можно было бы проверить, что книга book_name действительно в списке `favorites`, например, с помощью конструкции `in/not in`

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize(
отлично! хороший тест

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 0
можно лучше: или `not in`

2023-07-03 06:48 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) != 1
нужно исправить: скорее явно проверить, что список пуст

2023-07-04 09:14 UTC, Vikhu23 commented on README.md
> +
Ужас, расписывал каждую проверку, какой метод и какая проверка, и ОР. Ничего не сохранилось как я понял

2023-07-04 10:01 UTC, Vikhu23 commented on tests.py
> +        assert len(collector.get_books_rating()) != 2
Fixed 
assert len(collector.get_books_rating()) == 1

2023-07-04 10:01 UTC, Vikhu23 commented on tests.py
> +        assert collector.get_book_rating('Горе от ума') != 10
Fixed 
 assert collector.get_book_rating('Горе от ума') == None

2023-07-04 10:01 UTC, Vikhu23 commented on tests.py
> +    def test_set_rating_book_less_than_1_not_setting(self, book_name):
Fixed 
@pytest.mark.parametrize(
        'rating',[-1,11,0]
    )
    def test_set_rating_book_less_than_1_or_set_rating_book_more_than_10_not_setting(self, book_name,rating):
        collector = BooksCollector()
        collector.add_new_book(book_name)
        collector.set_book_rating(book_name, rating)
        assert collector.get_book_rating(book_name) == 1

2023-07-04 10:06 UTC, Vikhu23 commented on tests.py
> +        assert collector.get_book_rating(book_name) != 11
Fixed in test
def test_set_rating_book_less_than_1_or_set_rating_book_more_than_10_not_setting(self, book_name,rating):

2023-07-04 10:07 UTC, Vikhu23 commented on tests.py
> +        assert collector.get_books_rating() != 0
fixed 
assert collector.get_book_rating(book_name) != 0

2023-07-04 10:15 UTC, Vikhu23 commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 0
Fixed 
assert book_name not in collector.get_list_of_favorites_books()

2023-07-04 10:15 UTC, Vikhu23 commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) != 1
Fixed 
assert len(collector.get_list_of_favorites_books()) == 0

2023-07-04 21:11 UTC, kadirovgm requested changes

2023-07-04 21:11 UTC, kadirovgm commented on .gitignore
> +.pytest_cache
супер

2023-07-04 21:11 UTC, kadirovgm commented on README.md
> +```python
можно лучше: выписывать сюда код явно лишнее :)) так не стоит делать больше

2023-07-04 21:11 UTC, kadirovgm commented on conftest.py
> +def book_rating():
в том плане, что частный кейс и можно было бы обойтись и без фикстуры

2023-07-04 21:11 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_books_rating()) == 1
верно

2023-07-04 21:11 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('Горе от ума') == None
верно, или правильнее is None

2023-07-04 21:11 UTC, kadirovgm commented on tests.py
> +        'rating',[-1,11,0]
супер!

2023-07-04 21:11 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating(book_name) != 0
нужно исправить: в файле main.py видим, что метод `add_new_book` при добавлении книги выставляет ему рейтинг = 1, так что проверка того, что рейтинг не равно нулю, здесь совсем не верное. Опять таки в тесте надо проверять явно, а не косвенно, надо четко проверить, что либо рейтинга нет (то есть None или 0), или его знаение по дефолту 1.

2023-07-04 21:11 UTC, kadirovgm commented on tests.py
> +        assert book_name not in collector.get_list_of_favorites_books()
верно

2023-07-05 21:50 UTC, kadirovgm approved these changes

2023-07-05 23:36 UTC, merged